version: '3.5'

volumes:
  mysql_data:


services:
  laravel-app:
    links:
      - mysql-db
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - DB_HOST=db
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app

  mysql-db:
    image: mariadb:10.5
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    networks:
      backend:
        aliases:
          - db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql-db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      ports:
        - '8080:80'
      networks:
        backend:
          aliases:
            - phpmyadmin

networks:
  backend:
    name: backend-network
